name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: arduino/compile-sketches@v1.0.1
      with:
        fqbn: esp32:esp32:esp32doit-devkit-v1
        sketch-paths: NES-MEP-UI
